[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.x"

[[constraint]]
  name = "github.com/awslabs/aws-lambda-go-api-proxy"
  version = "0.2.x"

[prune]
  go-tests = true
  unused-packages = true
